[build]
# プロジェクト固有のビルド設定
rustflags = ["-D", "warnings"]  # warningをエラーとして扱う

[env]
# 環境変数の設定
RUST_LOG = "debug"

[alias]
# 便利なエイリアス
check = "check --all-targets --all-features"
test = "test --all-features"
clippy = "clippy --all-targets --all-features -- -D warnings"
fmt = "fmt --all"
